<?xml version="1.0" encoding="UTF-8"?>
<project name="com_userreminder" basedir="." default="dist" description="Build package file for UserReminder extension">
    <target name="dirbuild">

        <!-- Main component -->
        <copy file="./language/en-GB/com_userreminder.ini" todir="${releasespath}/build/site/language" />
        <copy file="./administrator/language/en-GB/com_userreminder.ini" todir="${releasespath}/build/admin/language" />
        <copy file="./administrator/language/en-GB/com_userreminder.sys.ini" todir="${releasespath}/build/admin/language" />
        <copy todir="${releasespath}/build/admin">
            <fileset dir="./administrator/components/com_userreminder">
                <exclude name="userreminder.xml"></exclude>
            </fileset>
        </copy>
        <echo msg="3 - Copying site files" />
        <copy todir="${releasespath}/build/site">
            <fileset dir="./components/com_userreminder">
            </fileset>
        </copy>
        <copy file="./administrator/components/com_userreminder/userreminder.xml" todir="${releasespath}/build/" />

        <!-- Plugins -->
        <copy todir="${releasespath}/build/plugins/plg_system_userreminder">
            <fileset dir="./plugins/system/userreminder"></fileset>
        </copy>

        <!-- Package files -->
        <copy file="./pkg_script.php" todir="${releasespath}/build" />
        <copy file="./pkg_userreminder.xml" todir="${releasespath}/build" />


    </target>
    <target name="dist" depends="dirbuild">

        <reflexive>
            <fileset dir="${releasespath}/build/.">
                <include name="*.xml" />
                <include name="*/*.xml" />
                <include name="*/*/*.xml" />
                <include name="*/*/*/*.xml" />
                <include name="*/*/*/*/*.xml" />
            </fileset>
            <filterchain>
                <replaceregexp>
                    <regexp pattern="##VERSION##" replace="${version}"/>
                </replaceregexp>
            </filterchain>
        </reflexive>


        <echo msg="Creating archive..." />
        <zip destfile="${releasespath}/com_userreminder_v${version}.zip" basedir="${releasespath}/build/"/>
        <echo msg="Files copied and compressed in build directory OK!" />
        <delete dir="${releasespath}/build/" verbose="true" failonerror="true" />
        <echo msg="Build File removed" />
    </target>
</project>