<?php
/**
 * JoomCRM
 *
 * @author     JoomBoost <support@joomboost.com>
 * @copyright  Copyright (C) 2018 Joomboost.com All Rights Reserved.
 * @license    http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * Website: https://www.joomboost.com
 */

defined('_JEXEC') or die;

\Joomla\CMS\Form\FormHelper::loadFieldClass('list');
/**
 * Voteradio Field class.
 *
 * @since  3.8.0
 */
class JFormFieldScheduleron extends \Joomla\CMS\Form\Field\ListField
{

    protected $type = 'Scheduleron';

    protected function getInput()
    {
        $input = parent::getInput(); // TODO: Change the autogenerated stub

        $timeHourText = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_HOUR');
        $selectTime = \Joomla\CMS\Language\Text::_('USERREMINDER_SELECT_TIME');
        $weekDayText = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY1');
        $weekDayText2 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY2');
        $weekDayText3 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY3');
        $weekDayText4 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY4');
        $weekDayText5 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY5');
        $weekDayText6 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY6');
        $weekDayText7 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_WEEKDAY7');
        $timeMonthday1 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_MONTHDAY1');
        $timeMonthday2 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_MONTHDAY2');
        $timeMonthday3 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_MONTHDAY3');
        $timeMonthday4 = \Joomla\CMS\Language\Text::_('USERREMINDER_TIME_MONTHDAY4');

        $scheduledExecutionTime = \Joomla\CMS\Component\ComponentHelper::getParams('com_userreminder')->get('scheduledExecutionTime',0);


        $input.= <<<js
<script> 
    var scheduledTime = $scheduledExecutionTime;
    var timeOptions =new Array();
    timeOptions[0] = {"0" : "$selectTime"};
    timeOptions[1] = {
        "0" : "0:00 $timeHourText",
        "1" : "1:00 $timeHourText",
        "2" : "2:00 $timeHourText",
        "3" : "3:00 $timeHourText",
        "4" : "4:00 $timeHourText",
        "5" : "5:00 $timeHourText",
        "6" : "6:00 $timeHourText",
        "7" : "7:00 $timeHourText",
        "8" : "8:00 $timeHourText",
        "9" : "9:00 $timeHourText",
        "10" : "10:00 $timeHourText",
        "11" : "11:00 $timeHourText",
        "12" : "12:00 $timeHourText",
        "13" : "13:00 $timeHourText",
        "14" : "14:00 $timeHourText",
        "15" : "15:00 $timeHourText",
        "16" : "16:00 $timeHourText",
        "17" : "17:00 $timeHourText",
        "18" : "18:00 $timeHourText",
        "19" : "19:00 $timeHourText",
        "20" : "20:00 $timeHourText",
        "21" : "21:00 $timeHourText",
        "22" : "22:00 $timeHourText",
        "23" : "23:53 $timeHourText"
    }
    timeOptions[2] = {
        "1" : "$weekDayText",
        "2" : "$weekDayText2",
        "3" : "$weekDayText3",
        "4" : "$weekDayText4",
        "5" : "$weekDayText5",
        "6" : "$weekDayText6",
        "7" : "$weekDayText7"
    }
    timeOptions[3] = {
        "1" : "1$timeMonthday1",
        "2" : "2$timeMonthday2",
        "3" : "3$timeMonthday3",
        "4" : "4$timeMonthday4",
        "5" : "5$timeMonthday4",
        "6" : "6$timeMonthday4",
        "7" : "7$timeMonthday4",
        "8" : "8$timeMonthday4",
        "9" : "9$timeMonthday4",
        "10" : "10$timeMonthday4",
        "11" : "11$timeMonthday4",
        "12" : "12$timeMonthday4",
        "13" : "13$timeMonthday4",
        "14" : "14$timeMonthday4",
        "15" : "15$timeMonthday4",
        "16" : "16$timeMonthday4",
        "17" : "17$timeMonthday4",
        "18" : "18$timeMonthday4",
        "19" : "19$timeMonthday4",
        "20" : "20$timeMonthday4",
        "21" : "21$timeMonthday1",
        "22" : "22$timeMonthday2",
        "23" : "23$timeMonthday3",
        "24" : "24$timeMonthday4",
        "25" : "25$timeMonthday4",
        "26" : "26$timeMonthday4",
        "27" : "27$timeMonthday4",
        "28" : "28$timeMonthday4",
        "29" : "29$timeMonthday4",
        "30" : "30$timeMonthday4",
        "31" : "31$timeMonthday1"
    }
document.getElementById('jform_paramsscheduledExecutionType').setAttribute("onChange", "handleSelectChange(this);");
    function handleSelectChange(selectObj)
    {
        var selectedIndex = selectObj.selectedIndex;
        var selectedValue = selectObj.options[selectObj.selectedIndex].value;
        var timeSelectBox = document.getElementById('jform_scheduledExecutionTime');
        var html = "";
        timeSelectBox.innerHTML = html;
        for (var i in timeOptions[selectedIndex])
        {
            //alert(timeOptions[selectedIndex][i]);
            html += '<option value="'+i+'">'+timeOptions[selectedIndex][i]+'</option>';
            var opt = document.createElement('OPTION');
            opt.text = timeOptions[selectedIndex][i];
            opt.value = i+"";
            document.getElementById('jform_scheduledExecutionTime').options.add(opt);
        }
    }
    handleSelectChange(document.getElementById('jform_paramsscheduledExecutionType'));
    document.getElementById('jform_scheduledExecutionTime').value = ""+scheduledTime;
    </script>
js;


        return $input;


    }


    public function getOptions($isFilter = false){


        $options = array();


        return $options;
    }




}
